# SQL Hands-On

### Importing Libraries

In [ ]:
import sqlalchemy as db
import pandas as pd

### Creating a SQL Database with SQL Alchemy

The first establish a "database engine". If the path directs to existing database, we can access that database. If the path directs to a database that is not yet existent, it will be created

In [ ]:
# adapt this path to your setup
engine = db.create_engine("sqlite:///acmdatabase")

Then, we need to connect the created database engine

In [ ]:
engine.connect()

In [ ]:
inspector = db.inspect(engine)
inspector.get_table_names() # the database is empty

### Load ACM data with Pandas

Load Excelfiles of ACM case as dataframes

In [ ]:
survey = pd.read_excel("https://github.com/casbdai/notebooks2023/raw/main/Module2/SQL/TV_Survey_Data.xlsx")
survey.info()

Load Excelfiles of ACM case as dataframes

In [ ]:
intentionality = pd.read_excel("https://github.com/casbdai/notebooks2023/raw/main/Module2/SQL/TV_Intentionality_Data.xlsx")
intentionality.info()

### Write loaded data into acmdatabase with Pandas

Write survey dataframe into acmdatabase using pandas

In [ ]:
survey.to_sql('survey', con=engine, if_exists="replace", index=False)

inspector = db.inspect(engine)
inspector.get_table_names() #now we have created the table survey

Write intentionality dataframe into acmdatabase using pandas

In [ ]:
intentionality.to_sql('intentionality', con=engine, if_exists="replace", index=False)

inspector = db.inspect(engine)
inspector.get_table_names() #now we have created the table intentionality

### Select Statements

Select entire table

In [ ]:
pd.read_sql(db.text("SELECT * FROM survey;"), engine.connect())

Select Variables "GRP" and "ProgramName" from table survey

In [ ]:
pd.read_sql(db.text("SELECT GRP, ProgramName FROM survey;"), engine.connect())

Select the variables "gravity", "relatability" and "edge" from survey

In [ ]:
pd.read_sql(db.text("SELECT gravity, relatability, edge FROM survey;"), engine.connect())

Select all variables from table intentionality

In [ ]:
pd.read_sql(db.text("SELECT * FROM intentionality;"), engine.connect())

### Aliases

Using aliases, i.e., "AS" we can rename single or all variables in our SQL query

In [ ]:
pd.read_sql(db.text("SELECT GRP AS 'Gross Rate Point', ProgramName AS Program FROM survey;"), engine.connect())

From the table intentionality select the variables "Program Name" and "Intenationality". you want the variable names to be all caps (e.g., PROGRAM NAME)

In [ ]:
pd.read_sql(db.text("SELECT ProgramName AS 'PROGRAM NAME', Intentionality AS INTENTIONALITY FROM intentionality;"), engine.connect())

### Where-Clauses

With where clauses, you can make specific selections of the data, comparable to .loc() in Pandas

In [ ]:
pd.read_sql(db.text("SELECT ProgramName, Spend, DateAired FROM survey WHERE ProgramName='See and Sold';"), engine.connect())

You can use all kind of boolean operators: AND  OR  >  <  =  !=

In [ ]:
pd.read_sql(db.text("SELECT ProgramName, Spend FROM survey WHERE ProgramName='See and Sold' AND Spend > 40;"), engine.connect())

Select all programs with an intentionality score of bigger than 0.5 from table intentionality

In [ ]:
pd.read_sql(db.text("SELECT ProgramName, Intentionality FROM intentionality WHERE Intentionality > 0.5;"), engine.connect())

Select the "gravity" and "edge" variables for the programs "See and Sold" and "New Gal" from the table survey

In [ ]:
pd.read_sql(db.text("SELECT edge, gravity, ProgramName FROM survey WHERE ProgramName='See and Sold' OR ProgramName = 'New Gal';"), engine.connect())

### Selecting Data from Multiple Tables - Where SQL can become complicated :)

First try

In [ ]:
pd.read_sql(db.text("SELECT A.GRP, B.Intentionality FROM survey A, intentionality B WHERE A.ProgramName = B.ProgramName;"), engine.connect())

Better Try - We need to apply the where clause to all three criteria in the two data sets

In [ ]:
pd.read_sql(db.text("SELECT A.GRP, B.Intentionality FROM survey A, intentionality B WHERE A.ProgramName = B.ProgramName AND A.DateAired=B.date AND A.IndustryAdType = B.IndustryAdType;"), engine.connect())

This is equivalent to an inner join - we will look at that in greater detail in Pandas :)